package ru.example.demo.helper.objects;

public enum BreadcrumbsKind {
    MUNICIPALITIES,
    MUNICIPALITY_CREATE,
    FEDERAL_SUBJECTS,
    MUNICIPALITY_TYPES,
    MUNICIPALITY,
    MUNICIPALITY_FORECAST,
    MUNICIPALITY_WATER_BODIES,
    WATER_BODY,
    WATER_BODY_CROWDED_PLACES,
    WATER_BODY_SMALL_VESSELS,
    CROWDED_PLACE,
    SMALL_VESSEL,
    FEDERAL_SUBJECT,
    FEDERAL_SUBJECT_FORECAST,
    FEDERAL_SUBJECT_CREATE,
    PROTECTIVE_MEASURES,
    PROTECTIVE_MEASURE,
    USERS,
    USER_CREATE,
    USER
}
